name: Publish to nuget.org

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Publish to nuget.org
      run: make publish NUGET_KEY=${{ secrets.NUGET_ORG_KEY }}
