name: Build pull requests

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0
    
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: dynamodb
          DEBUG: "1"
          HOSTNAME_EXTERNAL: localstack
        options: >-
          --name=localstack
          --health-cmd="curl -sS 127.0.0.1:4566 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: export AWS_DYNAMODB_URL=http://localstack:4566 && dotnet test
